# Generated by Django 4.2.11 on 2024-06-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0012_rename_gallery_galleryembed_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-year'], 'verbose_name_plural': 'Galleries'},
        ),
    ]
