# Generated by Django 4.2.11 on 2024-05-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery_name',
        ),
    ]
