# Generated by Django 4.2.11 on 2024-05-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0002_galleryembed_remove_galleryimage_gallery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='')),
                ('headline', models.CharField(max_length=500)),
                ('link_url', models.CharField(max_length=10000)),
            ],
        ),
    ]
