# Generated by Django 4.2.11 on 2024-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0004_carouselimage_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='gallerylink',
            name='image_file',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='image_url',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerylink',
            name='image_url',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
