# Generated by Django 4.2.11 on 2024-06-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0005_remove_carouselimage_image_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryembed',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='gallerylink',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='galleryembed',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='gallerylink',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
