# Generated by Django 4.2.11 on 2024-06-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0007_year_galleryembed_year_galleryimage_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={},
        ),
        migrations.RemoveField(
            model_name='year',
            name='the_order',
        ),
    ]
