# Generated by Django 4.2.11 on 2024-06-12 06:37

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0009_rename_year_gallery_rename_year_galleryembed_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('sponsor_page', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diwalibackend.sponsorpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=10000)),
                ('alternate_text', models.CharField(default='', max_length=10000)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('section', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diwalibackend.sponsorsection')),
            ],
            options={
                'ordering': ['the_order'],
                'abstract': False,
            },
        ),
    ]
