# Generated by Django 4.2.11 on 2024-06-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0010_sponsorpage_sponsorsection_sponsorimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['year'], 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='sponsorpage',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='sponsorsection',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='sponsorsection',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
