# Generated by Django 4.2.11 on 2024-06-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0011_alter_gallery_options_alter_sponsorpage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryembed',
            old_name='gallery',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='gallery',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='gallerylink',
            old_name='gallery',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='sponsorimage',
            old_name='section',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='sponsorsection',
            old_name='sponsor_page',
            new_name='parent',
        ),
    ]
