# Generated by Django 4.2.11 on 2024-06-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0013_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorpage',
            options={'ordering': ['-year']},
        ),
    ]
