# Generated by Django 4.2.11 on 2024-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwalibackend', '0014_alter_sponsorpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='full_date',
            field=models.CharField(default='', max_length=500),
        ),
    ]
