name: Build and deploy Node.js and Django app to Azure Web App - MelbourneDiwaliTest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          npm install @google/generative-ai scroll-into-view
          npm run build
        working-directory: react

      - name: Zip frontend artifact
        run: zip -r react.zip ./*
        working-directory: react/build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-artifact
          path: react/build/react.zip

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and build backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: diwali

      - name: Zip backend artifact
        run: zip -r diwali.zip ./*
        working-directory: diwali

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: diwali-artifact
          path: diwali/diwali.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: react-artifact

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: diwali-artifact

      - name: Unzip frontend artifact
        run: unzip react.zip -d ./react

      - name: Unzip backend artifact
        run: unzip diwali.zip -d ./diwali

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: ./react

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: ./diwali
